apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: tzulingk-moe
spec:
  ports:
    - port: 2379
      name: client
      targetPort: 2379
    - port: 2380
      name: peer
      targetPort: 2380
  selector:
    app: etcd
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: tzulingk-moe
spec:
  serviceName: etcd-service
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.9
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          value: "etcd-0"
        - name: ETCD_DATA_DIR
          value: "/var/lib/etcd"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd-service:2379"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://etcd-0.etcd-service:2380"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_INITIAL_CLUSTER
          value: "etcd-0=http://etcd-0.etcd-service:2380"
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: "new"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: "etcd-cluster-1"
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/lib/etcd
      volumes:
      - name: etcd-storage
        emptyDir: {}



